name: release
run-name: Release Packages
on:
  push:
    tags:
      - v*
jobs:
  build-packages-workflow:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build-packages-workflow
    steps:
    - name: Download pg_restore_points Artifacts
      uses: actions/download-artifact@v3
      with:
        name: packages

    - name: Upload to release
      uses: pyTooling/Actions/releaser@r0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          *.deb
          *.rpm